package feature.category.common.domain.model

enum class CategoryIconName(val key: String) {
    Tag("tag"),
    Food("food"),
    Bus("bus"),
    Shopping("shopping"),
    TShirt("tshirt"),
    IPhone("iphone"),
    Book("book"),
    House("house"),
    Map("map"),
    Medical("medical"),
    MortarBoard("mortar-board"),
    Coffee("coffee"),
    Gift("gift"),
    OfficeChair("office-chair"),
    Stroller("stroller"),
    CreditCard("credit-card"),
    Transportation("transportation"),
    Electricity("electricity"),
    Rent("rent"),
    Entertainment("entertainment"),
    Gym("gym"),
    Insurance("insurance"),
    Loan("loan"),
    Salary("salary"),
    Vacation("vacation"),
    Car("car"),
    Grocery("grocery"),
    Subscription("subscription"),
    Charity("charity"),
    Tax("tax")
}
